# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: publish npm

on:
  release:
    types: [created]

jobs:
  build:
    name: Publish package on npm
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm run build-lib-prod
    - run: npm publish ./dist/b3-ol-map --access public 
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
